language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install:
  - "npm install -g grunt-cli"
  - "npm i -g jasmine-node"
  currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'game-server' ]; then cd .. && eval "mv $currentfolder
    npm test;